### ISSUE TITLE
OData V4 Lambda expression raises sqlite error

### ISSUE THREAD

**Issue by BenReim** [SAP-samples/cloud-cap-samples#131]
When running the bookshop sample and querying a HTTP call that contains a lambda expressions according to the odata specification, a sql error is being thrown.

**Request**
```http
### Books with a french translation
GET http://localhost:4004/admin/Books
    ?$top=5
    &$select=title
    &$expand=texts
    &$filter=texts/any(t:t/locale eq 'fr')
```

**Response**
```
{
  "error": {
    "code": "500",
    "message": "SQLITE_ERROR: near \"SELECT\": syntax error"
  }
}

```

**Comment by Vest** [comment]
It seems that CAP doesn't create a correct SQL request. Your example can be simplified to
```
http://localhost:4004/admin/Books?$filter=texts/any(t:t/locale eq 'fr')
```
the generated SQL will be:
```sql
SELECT createdAt, createdBy, modifiedAt, modifiedBy, ID, title, descr, stock, price, author_ID, genre_ID, currency_code
FROM localized_AdminService_Books
WHERE ( ID ) = any ( SELECT ID FROM AdminService_Books_texts WHERE locale = ? )
ORDER BY ID
ASC LIMIT ?
```
The syntax error is right after WHERE --> **any** is unknown to the DB.

By the way, it is funny, but you can even crash the process if you play with the requests.

**Comment by chgeo** [comment]
@David-Kunz can you check this?

@BenReim we would like to close down this issue channel.  Please report further questions over on our [community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce).
Thanks.

**Comment by David-Kunz** [comment]
Hi @Vest,

Currently, we only support `any` for SAP HANA, but it's planned to support it also for SQLite.

In development mode, we always crash the server if something fishy happens. Otherwise we wouldn't notice! ([let it crash](http://stratus3d.com/blog/2020/01/20/applying-the-let-it-crash-philosophy-outside-erlang/#:~:text=Erlang%20is%20known%20for%20its,are%20fault%20tolerant%20and%20reliable.&text=The%20Let%20It%20Crash%20philosophy%20is%20an%20approach%20to%20error,certain%20faults%20to%20go%20unhandled.))

Best regards,
David

**Comment by chgeo** [comment]
Closing this issue as we want to shut down this issue channel.  Please report further questions over on our community.
Thanks.
