### ISSUE TITLE
 Cannot find local module '../../../db/src/data/model

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [SAP-samples/cloud-cap-samples#30]
index.cds
```swift
using from './lib/cds/solicitation';

solicitation.cds
namespace "sprolimslabservapi";

using sprolimslabservapi.data.model as app from '../../../db/src/data/model';

service solicitation_service {
  entity solicitation as projection on app.solicitation;
}
```
db structure
![image](https://user-images.githubusercontent.com/9791364/75051733-2d0b1d80-54ad-11ea-84ab-aea1d25902df.png)

srv structure
![image](https://user-images.githubusercontent.com/9791364/75051778-4318de00-54ad-11ea-8f61-eba06c08d49f.png)

access `.....br10.hana.ondemand.com/v2/`
 Error: `Cannot find local module '../../../db/src/data/model'\n`

**Comment by chgeo** [comment]
Please add the steps to reproduce, or the link to the repository.

**Comment by luizcarlospedrosogomes** [comment]
step 1:  npm install @sap/cds

step 2: create model.cds, solicitation.cds and index.cds

step 3: cf push app


this project using xs advance and are migrate to cds.

**Comment by chgeo** [comment]
Ok, I see  2 pitfalls here:
- `cf push` needs to be executed with a compiled model, which is produced by `cds build/all`
- For the build to work w/o further configuration, you should stick to the [standard project layout](https://cap.cloud.sap/docs/get-started/projects#default-project-layouts), which means
  - have your DB model files flat in `db/` instead of in `db/src/data`
  - have your service model files flat in `srv/` instead of in `srv/lib/data`.  If you absolutely cannot work with this, then add a `srv/index.cds` file which imports the rest from `srv/lib/data` (see [example](https://github.com/SAP-samples/cloud-cap-samples/blob/master/packages/bookshop/app/index.cds)).

Then follow the steps in the [Deploy to Cloud](https://cap.cloud.sap/docs/advanced/deploy-to-cloud#deploy-using-cf-push) docs.

**Comment by luizcarlospedrosogomes** [comment]
Yes

i am using https://github.com/gregorwolf/bookshop-nodejs

but this repository nodes server not working with cds.

**Comment by chgeo** [comment]
In the repo, I see that mta deployment is [enabled](https://github.com/gregorwolf/bookshop-nodejs/blob/master/package.json#L32) for CF.  So calling
```sh
npm run build:cf
cf deploy <mtarFile>
```
should do the trick.  

For further questions, @gregorwolf should be able to help you as he is the owner of the repo.

**Comment by chgeo** [comment]
Closing this one, assuming the issue got resolved.
