### ISSUE TITLE
import csv data

### ISSUE THREAD

**Issue by jun-wu** [SAP-samples/cloud-cap-samples#48]
Hi,
I am following this exercise https://github.com/SAP-samples/cloud-cap-nodejs-codejam/tree/master/exercises/04
if I put schema.cds under db/src folder,  no csv files are imported during cds deploy.
it only works if I put schema.cds under db folder directly. is there any command option to help?
table are created in database no matter where the cds file is located.
is it expected like this?
Best regards,
Jun

**Comment by chgeo** [comment]
Hi,

this is expected behavior.  There is a [standard project layout](https://cap.cloud.sap/docs/get-started/projects#default-project-layouts) which recommends you putting `cds` files in `db/ ` directly.  Then, the deployment checks for `csv/` or `data/` folders _next_ to your model files, which means if you put the `cds` files in `db/src`, then `db/csv` wouldn't match.
Use `db/src/` should only be used in for native SAP HANA files.

Regards,
Christian
