### ISSUE TITLE
How to setup the Fiori part of the demo apps?

### ISSUE THREAD

**Issue by sfdfklskldf** [SAP-samples/cloud-cap-samples#77]
As you see in the screenshot the SAP Business Application Studio points to a different server for the SAPUI5 files. I used the example from here: https://github.com/SAP-samples/cloud-cap-samples/tree/openSAP-week3-unit1 

Is there a way to serve the UI5 libs from the cloud instance?

![grafik](https://user-images.githubusercontent.com/9265604/81698538-72186d80-9466-11ea-9aa2-c4e82408b7c3.png)

**Comment by chgeo** [comment]
> SAP Business Application Studio points to a different server for the SAPUI5 files?

What do you mean here?  The URL https://sapui5.hana.ondemand.com/resources/sap-ui-core.js is to my knowledge the canonical address of SAP UI5.

Anyways.. this looks like a browser issue, i.e. the `net::ERR_BLOCKED_BY_CLIENT` error is caused by your _client_ network, not by the Studio.
I can successfully open the URL above in my browser.  Doesn't this work for you?

@offer8: have seen this before?

**Comment by offer8** [comment]
Nope, @amiramw do familiar with this one?

**Comment by sfdfklskldf** [comment]
@chgeo The Fiori App is served by the trial account and SAP Business Application Studio as in the videos. But if I try to access the Fiori part I got this error in the browser. Because the browser blocks loading the URL because the URL is not from the same source. So I have a normal chrome browser. Would be better the resources of SAPUI5 are served from the cloud (same url) as it is done with WEB IDE. Maybe by using a reverse proxy.

**Comment by chgeo** [comment]
I see that the SAP UI5 server sends `access-control-allow-origin: *` for the resource, so this can't be a CORS issue (if this is what you are suggesting).  

We also have not heard this issue from other users.

Some [resources](https://www.keycdn.com/support/how-to-solve-err-blocked-by-client) out there indicate that ad blockers could cause `net::ERR_BLOCKED_BY_CLIENT`.  Is there anything like this running on your local machine?

**Comment by sbarzaghialteaup** [comment]
Hi,

I had a fiori elements app running locally on my pc without problems up to yesterday.

This morning CORS error on this single file:
"https://sapui5.hana.ondemand.com/shells/sandbox/fioriSandboxConfig.json".

All the resourses return with"access-control-allow-origin: *" except fioriSandboxConfig.json.
But now the problem changed, 404 on fioriSandboxConfig.json file instead of CORS error.

So I create a local /appconfig/fioriSandboxConfig.json and now I get 404 on:
https://sapui5.hana.ondemand.com/resources/sap/fe/templates/ListReport/Component-preload.js

Something strange seems to be happening on sapui5.hana.ondemand.com?

**Comment by sbarzaghialteaup** [comment]
No problems using release 1.76.0:
https://sapui5.hana.ondemand.com/1.76.0/resources/sap-ui-core.js

**Comment by sbarzaghialteaup** [comment]
Another fiori elements app generated with webide works.

It use the component sap.suite.ui.generic.template.ListReport instead of sap.fe.templates.ListReport 
I cannot find documentation about sap.fe.templates.ListReport :-)

**Comment by sfdfklskldf** [comment]
You are right it was something in Chrome. Looks like the Privacy Badger had issues with that. https://privacybadger.org/ Normally I do not notice any issues with that plugin at all.

Sorry for that, but maybe someone else will have this issue as well.

**Comment by chgeo** [comment]
Sure.  Good to know it's working now.
